repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  name: rn-diff-purge

  description: Easier React Native upgrades by clearly exposing changes from a version to another. :rocket: And what better way than to purge, init, then diff? Spoiler: there's no better way. 😎

  homepage: https://pvinis.github.io/purge-web

  private: false

  has_issues: true
  has_wiki: true

  default_branch: master
  
